import type { Metadata } from "next";
import { Outfit } from "next/font/google";
import "./globals.css";
import { ToastContainer } from "react-toastify";
import NextTopLoader from "nextjs-toploader";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const outFitFont = Outfit({
  variable: "--font-outfit",
  subsets: ["latin"],
});
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${outFitFont.variable} antialiased`}>
        {children}
        <ToastContainer />
        <NextTopLoader
          color="#2299DD"
          height={3}
          showSpinner={true}
          zIndex={1600}
        />
      </body>
    </html>
  );
}
