import type { Metadata } from "next";
import { Outfit, Inter } from "next/font/google";
import "./globals.css";
import { ToastContainer } from "react-toastify";
import NextTopLoader from "nextjs-toploader";
import Script from "next/script";
import { Analytics } from "@vercel/analytics/next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const outFitFont = Outfit({
  variable: "--font-outfit",
  subsets: ["latin"],
});
const interFont = Inter({ variable: "--font-inter", subsets: ["latin"] });

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="tr">
      <body
        className={`${outFitFont.variable} font-inter ${interFont.variable} antialiased`}
      >
        {children}
        <ToastContainer />
        <NextTopLoader
          color="#CE0F2E"
          height={3}
          showSpinner={true}
          zIndex={1600}
        />
        {process.env.NODE_ENV === "production" && (
          <>
            <Script
              src={`https://www.googletagmanager.com/gtag/js?id=G-EF71XJ5DN7`}
              strategy="afterInteractive"
            />
            <Script id="google-analytics" strategy="afterInteractive">
              {`
              window.dataLayer = window.dataLayer || [];
              function gtag(){dataLayer.push(arguments);}
              gtag('js', new Date());

              gtag('config', 'G-EF71XJ5DN7');
            `}
            </Script>
          </>
        )}
        <Analytics />
      </body>
    </html>
  );
}
