import type { Metadata } from "next";
import { Outfit, Inter } from "next/font/google";
import "./globals.css";
import { ToastContainer } from "react-toastify";
import NextTopLoader from "nextjs-toploader";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const outFitFont = Outfit({
  variable: "--font-outfit",
  subsets: ["latin"],
});
const interFont = Inter({ variable: "--font-inter", subsets: ["latin"] });

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="tr">
      <body
        className={`${outFitFont.variable} font-inter ${interFont.variable} antialiased`}
      >
        {children}
        <ToastContainer />
        <NextTopLoader
          color="#CE0F2E"
          height={3}
          showSpinner={true}
          zIndex={1600}
        />
      </body>
    </html>
  );
}
